// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnydXX2YFLITxH6bXiX_DhUa5dPGhxy_c',
    appId: '1:932061021512:web:f9f87852578d0712f15f7d',
    messagingSenderId: '932061021512',
    projectId: 'controle-de-abasteciment-d9f7a',
    authDomain: 'controle-de-abasteciment-d9f7a.firebaseapp.com',
    storageBucket: 'controle-de-abasteciment-d9f7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0EbnhcjDZQt0hjHoRsolW9dgR24IixUQ',
    appId: '1:932061021512:android:63c6ea9ac1dd252ef15f7d',
    messagingSenderId: '932061021512',
    projectId: 'controle-de-abasteciment-d9f7a',
    storageBucket: 'controle-de-abasteciment-d9f7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDud1ybCKnPe4N8GGckIfQ6xLzflLgXn0',
    appId: '1:932061021512:ios:2f5119869b666f65f15f7d',
    messagingSenderId: '932061021512',
    projectId: 'controle-de-abasteciment-d9f7a',
    storageBucket: 'controle-de-abasteciment-d9f7a.firebasestorage.app',
    iosBundleId: 'com.example.controleDeAbastecimentoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDud1ybCKnPe4N8GGckIfQ6xLzflLgXn0',
    appId: '1:932061021512:ios:2f5119869b666f65f15f7d',
    messagingSenderId: '932061021512',
    projectId: 'controle-de-abasteciment-d9f7a',
    storageBucket: 'controle-de-abasteciment-d9f7a.firebasestorage.app',
    iosBundleId: 'com.example.controleDeAbastecimentoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnydXX2YFLITxH6bXiX_DhUa5dPGhxy_c',
    appId: '1:932061021512:web:f26b81c8df7cae10f15f7d',
    messagingSenderId: '932061021512',
    projectId: 'controle-de-abasteciment-d9f7a',
    authDomain: 'controle-de-abasteciment-d9f7a.firebaseapp.com',
    storageBucket: 'controle-de-abasteciment-d9f7a.firebasestorage.app',
  );
}
